// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package follow

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO following (follower_id, following_id) VALUES ($1, $2)
ON CONFLICT (follower_id, following_id) DO NOTHING
RETURNING follower_id, following_id, created_at
`

type CreateParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Following, error) {
	row := q.db.QueryRow(ctx, create, arg.FollowerID, arg.FollowingID)
	var i Following
	err := row.Scan(&i.FollowerID, &i.FollowingID, &i.CreatedAt)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM following WHERE follower_id = $1 AND following_id = $2
`

type DeleteParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.FollowerID, arg.FollowingID)
	return err
}

const existByID = `-- name: ExistByID :one
SELECT EXISTS (
    SELECT 1 FROM following WHERE follower_id = $1 AND following_id = $2
) AS exists
`

type ExistByIDParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) ExistByID(ctx context.Context, arg ExistByIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existByID, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
