// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package comment

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	AuthorID  pgtype.UUID
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Post struct {
	ID        uuid.UUID
	Title     pgtype.Text
	Content   pgtype.Text
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	IsActive       pgtype.Bool
	ExpirationDate pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
