// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package comment

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO comments (author_id, author_name, post_id, content) VALUES ($1, $2, $3, $4) RETURNING id, post_id, author_id, author_name, content, created_at, updated_at
`

type CreateParams struct {
	AuthorID   pgtype.UUID
	AuthorName pgtype.Text
	PostID     uuid.UUID
	Content    pgtype.Text
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Comment, error) {
	row := q.db.QueryRow(ctx, create,
		arg.AuthorID,
		arg.AuthorName,
		arg.PostID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const getAllByPostID = `-- name: GetAllByPostID :many
SELECT id, post_id, author_id, author_name, content, created_at, updated_at FROM comments WHERE post_id = $1
`

func (q *Queries) GetAllByPostID(ctx context.Context, postID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getAllByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, post_id, author_id, author_name, content, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE comments SET content = $1, updated_at = now() WHERE id = $2 RETURNING id, post_id, author_id, author_name, content, created_at, updated_at
`

type UpdateParams struct {
	Content pgtype.Text
	ID      uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Comment, error) {
	row := q.db.QueryRow(ctx, update, arg.Content, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
