// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package reaction

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createByCommentID = `-- name: CreateByCommentID :one
INSERT INTO reactions (comment_id, user_id, reaction_type, content_type)
VALUES ($1, $2, $3, 'COMMENT')
ON CONFLICT (comment_id, user_id)
    WHERE content_type = 'COMMENT'
    DO UPDATE SET reaction_type = EXCLUDED.reaction_type, updated_at = now()
RETURNING id, post_id, comment_id, user_id, reaction_type, content_type, created_at, updated_at
`

type CreateByCommentIDParams struct {
	CommentID    pgtype.UUID
	UserID       uuid.UUID
	ReactionType ReactionType
}

func (q *Queries) CreateByCommentID(ctx context.Context, arg CreateByCommentIDParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, createByCommentID, arg.CommentID, arg.UserID, arg.ReactionType)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.CommentID,
		&i.UserID,
		&i.ReactionType,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createByPostID = `-- name: CreateByPostID :one
INSERT INTO reactions (post_id, user_id, reaction_type, content_type)
VALUES ($1, $2, $3, 'POST')
ON CONFLICT (post_id, user_id)
    WHERE content_type = 'POST'
    DO UPDATE SET reaction_type = EXCLUDED.reaction_type, updated_at = now()
RETURNING id, post_id, comment_id, user_id, reaction_type, content_type, created_at, updated_at
`

type CreateByPostIDParams struct {
	PostID       pgtype.UUID
	UserID       uuid.UUID
	ReactionType ReactionType
}

func (q *Queries) CreateByPostID(ctx context.Context, arg CreateByPostIDParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, createByPostID, arg.PostID, arg.UserID, arg.ReactionType)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.CommentID,
		&i.UserID,
		&i.ReactionType,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteByCommentIDAndUserID = `-- name: DeleteByCommentIDAndUserID :exec
DELETE FROM reactions WHERE comment_id = $1 AND user_id = $2
`

type DeleteByCommentIDAndUserIDParams struct {
	CommentID pgtype.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteByCommentIDAndUserID(ctx context.Context, arg DeleteByCommentIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteByCommentIDAndUserID, arg.CommentID, arg.UserID)
	return err
}

const deleteByPostIDAndUserID = `-- name: DeleteByPostIDAndUserID :exec
DELETE FROM reactions WHERE post_id = $1 AND user_id = $2
`

type DeleteByPostIDAndUserIDParams struct {
	PostID pgtype.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteByPostIDAndUserID(ctx context.Context, arg DeleteByPostIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteByPostIDAndUserID, arg.PostID, arg.UserID)
	return err
}

const existsByCommentIDAndUserID = `-- name: ExistsByCommentIDAndUserID :one
SELECT EXISTS (
    SELECT 1 FROM reactions WHERE comment_id = $1 AND user_id = $2 AND content_type = 'COMMENT'
) AS exists
`

type ExistsByCommentIDAndUserIDParams struct {
	CommentID pgtype.UUID
	UserID    uuid.UUID
}

func (q *Queries) ExistsByCommentIDAndUserID(ctx context.Context, arg ExistsByCommentIDAndUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByCommentIDAndUserID, arg.CommentID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByPostIDAndUserID = `-- name: ExistsByPostIDAndUserID :one
SELECT EXISTS (
    SELECT 1 FROM reactions WHERE post_id = $1 AND user_id = $2 AND content_type = 'POST'
) AS exists
`

type ExistsByPostIDAndUserIDParams struct {
	PostID pgtype.UUID
	UserID uuid.UUID
}

func (q *Queries) ExistsByPostIDAndUserID(ctx context.Context, arg ExistsByPostIDAndUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByPostIDAndUserID, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getByCommentIDAndUserID = `-- name: GetByCommentIDAndUserID :one
SELECT reactions.reaction_type FROM reactions WHERE comment_id = $1 AND user_id = $2
`

type GetByCommentIDAndUserIDParams struct {
	CommentID pgtype.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetByCommentIDAndUserID(ctx context.Context, arg GetByCommentIDAndUserIDParams) (ReactionType, error) {
	row := q.db.QueryRow(ctx, getByCommentIDAndUserID, arg.CommentID, arg.UserID)
	var reaction_type ReactionType
	err := row.Scan(&reaction_type)
	return reaction_type, err
}

const getByPostIDAndUserID = `-- name: GetByPostIDAndUserID :one
SELECT reactions.reaction_type FROM reactions WHERE post_id = $1 AND user_id = $2
`

type GetByPostIDAndUserIDParams struct {
	PostID pgtype.UUID
	UserID uuid.UUID
}

func (q *Queries) GetByPostIDAndUserID(ctx context.Context, arg GetByPostIDAndUserIDParams) (ReactionType, error) {
	row := q.db.QueryRow(ctx, getByPostIDAndUserID, arg.PostID, arg.UserID)
	var reaction_type ReactionType
	err := row.Scan(&reaction_type)
	return reaction_type, err
}
